apiVersion: apps/v1
kind: Deployment
metadata:
  name: muzammilsarwar-29172-redis-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-pod
  template:
    metadata:
      labels:
        name: redis-pod
    spec:
      containers:
        - name: muzammilsarwar-29172-redis-pod
          image: redis:latest
          ports:
            - containerPort: 2917