apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
 containers:
  - name: muzammilsarwar-29172-redis-pod
    image: redis:latest
    ports:
      - containerPort: 2917